accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'


urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
    url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),
    url(r'^profile/(?P<pk>\d+)/$', views.view_profile, name='profile'),
    url(r'^email/$', views.send_email, name='email'),
    url(r'^delete/founditem/(?P<pk>\d+)/$', views.DeleteFoundItem, name='found_delete'),
    url(r'^delete/lostitem/(?P<pk>\d+)/$', views.DeleteLostItem, name='lost_delete'),
]

mainpage/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from homepage.views import Home
from homepage import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Home.as_view(), name='home'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^private_messages/',include('private_messages.urls',namespace='private_messages')),
    url(r'^createlostitem/', views.CreateLostItem, name='createlostitem'),
    url(r'^createfounditem/', views.CreateFoundItem, name='createfounditem'),
]

private_messages/urls.py
from django.conf.urls import url
from . import views

app_name = 'private_messages'

urlpatterns = [
    url(r'^$',views.PrivateMessageList.as_view(),name='list'),
    url(r'^new/$',views.CreatePrivateMessage,name='new_message'),
    url(r'^text/$',views.CreateText,name='text'),
    url(r'^details/(?P<pk>\d+)/$',views.PrivateMessageDetail.as_view(),name='detail'),
    url(r'^delete/(?P<pk>\d+)/$',views.DeletePrivateMessage,name='delete'),
    url(r'^deletehome/(?P<pk>\d+)/$',views.DeletePrivateMessageHome,name='deletehome'),
]

private_messages/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth import get_user_model
User = get_user_model()

class PrivateMessageManager(models.Manager):
    def create_private_message(self, sender, recipient):
        private_message = self.create(sender = sender, recipient = recipient)
        return private_message

class PrivateMessage(models.Model):
    sender = models.ForeignKey(User, related_name="sender")
    recipient = models.ForeignKey(User, related_name="recipient")
    subject = models.CharField(max_length=256,unique=False)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now=True)
    viewed = models.BooleanField(default=False)
    objects = PrivateMessageManager()

    def __str__(self):
        return self.subject

private_messages/forms.py
from django.forms import ModelForm
from private_messages.models import PrivateMessage
from django import forms

class MessageForm(ModelForm):
    class Meta:
        model = PrivateMessage
        fields = ['recipient', 'subject', 'message']

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['recipient'].label = 'Recipient'
        self.fields['subject'].label = 'Subject'
        self.fields['message'].label = 'Message'

private_messages/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from . import forms
from private_messages.forms import MessageForm
from django.views import generic
from . import models
from private_messages.models import PrivateMessage
from django.contrib.auth import get_user_model
User = get_user_model()
from braces.views import SelectRelatedMixin
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404,JsonResponse
from django.shortcuts import get_object_or_404
from django.contrib import messages
from twilio.rest import Client
from mainpage.settings import TwilioId,TwilioToken

def CreateText(request):
    if request.method == "POST":
        response_data = {}
        if request.user.is_authenticated():
            sender = request.user
        message = request.POST.get('message')
        recipient_id = request.POST.get('recipient')
        recipient = get_object_or_404(User, pk=recipient_id)
        account_sid = TwilioId
        auth_token = TwilioToken
        recipient_phone_number = recipient.profile.phone_number
        sender_phone_number = sender.profile.phone_number
        client = Client(account_sid, auth_token)
        message = client.messages.create(
                "+"+recipient_phone_number,
                body=message,
                from_="+"+sender_phone_number)
        return JsonResponse(response_data)


def CreatePrivateMessage(request):
    if request.method == "POST":
        response_data = {}
        if request.user.is_authenticated():
            sender = request.user
        message = request.POST.get('message')
        subject = request.POST.get('subject')
        recipient_id = request.POST.get('recipient')
        recipient = get_object_or_404(User, pk=recipient_id)
        new_pm = PrivateMessage.objects.create_private_message(sender,recipient)
        new_pm.subject = subject
        new_pm.message = message
        new_pm.save()
        response_data['onMap'] = request.POST.get('onMap')
        response_data['recipient_id'] = recipient_id
        response_data['sender_id'] = sender.pk
        response_data['message_pk'] = new_pm.pk
        response_data['message'] = new_pm.message
        response_data['subject'] = new_pm.subject
        response_data['username'] = new_pm.sender.username
        response_data['recipient'] = new_pm.recipient.username
        return JsonResponse(response_data)

class PrivateMessageList(generic.TemplateView,SelectRelatedMixin,LoginRequiredMixin):
    model = models.PrivateMessage
    template_name = 'private_messages/privatemessage_list.html'

    def get(self, request, *args, **kwargs):
        message_form = MessageForm(self.request.GET or None)
        message_recipient = User.objects.prefetch_related('recipient').get(username__iexact=self.request.user.username)
        message_sender = User.objects.prefetch_related('sender').get(username__iexact=self.request.user.username)
        context = self.get_context_data(**kwargs)
        context['message_form'] = message_form
        context['users_inbox'] = message_recipient.recipient.all().order_by('-created_at')
        context['users_outbox'] = message_sender.sender.all().order_by('-created_at')
        return self.render_to_response(context)

class PrivateMessageDetail(SelectRelatedMixin,generic.DetailView):
    model = PrivateMessage

    select_related = ('sender','recipient')

    def get_object(self):
        object = super(PrivateMessageDetail, self).get_object()
        object.viewed = True
        object.save()
        return object

    def query_set(self):
        queryset = super().get_queryset()
        return queryset.filter(recipient = self.request.user)

def DeletePrivateMessage(request, **kwargs):
    private_message = get_object_or_404(PrivateMessage, pk=kwargs['pk'])
    private_message.delete()
    if request.is_ajax():
        response_data = {}
        response_data['pk'] = kwargs['pk']
        return JsonResponse(response_data)
    return redirect('private_messages:list')

def DeletePrivateMessageHome(request, **kwargs):
    private_message = get_object_or_404(PrivateMessage, pk=kwargs['pk'])
    private_message.delete()
    return redirect('home')

private_messages/templates/private_messages/_inbox_message.html
<div id="inbox-message-{{message.pk}}">
  {% if msgdetail == "True" %}
    <h3 class="subject_line">subject: {{message.subject}}</h3>
  {% else %}
    <h3 class="subject_line">subject: <a href="{% url 'private_messages:detail' pk=message.pk %}">{{message.subject}}</a></h3>
  {% endif %}
  <p id="sender-id-{{message.sender.pk}}">sender: {{message.sender.username}}</p>
  {% if message.sender.profile.emailable == False %}

    {% if from == "home" %}

      <p id="reply-options-{{message.pk}}">
        {% if message.sender.username != request.user.username and not hide_delete %}
          <button id='reply-button-{{message.pk}}' class='reply-button btn btn-primary' type='button' name='button'>Reply</button>
          {% if message.sender.profile.textable == True %}
            <button id='text-button-{{message.pk}}' class='text-button btn btn-primary' type='button' name='button'>Text</button>
          {% endif %}
          <a class='pm-delete' href="{% url 'private_messages:deletehome' pk=message.pk %}" title="delete" class="btn btn-simple">
            <span class="glyphicon glyphicon-remove text-danger"></span>
            <span class="text-danger icon-label">Delete</span>
          </a>
        {% endif %}
      </p>

    {% else %}

      <p id="reply-options-{{message.pk}}">
        {% if message.sender.username != request.user.username and not hide_delete %}
          <button id="reply-button-{{message.pk}}" class="reply-button btn btn-primary" type="button" name="button">Reply</button>
          {% if message.sender.profile.textable == True %}
            <button id="text-button-{{message.pk}}" class="text-button btn btn-primary" type="button" name="button">Text</button>
          {% endif %}
          <a class='pm-delete' href="{% url 'private_messages:delete' pk=message.pk %}" title="delete" class="btn btn-simple">
            <span class="glyphicon glyphicon-remove text-danger"></span>
            <span class="text-danger icon-label">Delete</span>
          </a>
        {% endif %}
      </p>

    {% endif %}

  {% else %}

    {% if from == "home" %}
      <p id="reply-options-{{message.pk}}">
        {% if message.sender.username != request.user.username and not hide_delete %}
          <button id="reply-button-{{message.pk}}" class="reply-button btn btn-primary" type="button" name="button">Reply</button>
          <button id="email-button-{{message.pk}}" class="email-button btn btn-primary" type="button" name="button">Email</button>
          {% if message.sender.profile.textable == True %}
            <button id="text-button-{{message.pk}}" class="text-button btn btn-primary" type="button" name="button">Text</button>
          {% endif %}
          <a class='pm-delete' href="{% url 'private_messages:deletehome' pk=message.pk %}" title="delete" class="btn btn-simple">
            <span class="glyphicon glyphicon-remove text-danger"></span>
            <span class="text-danger icon-label">Delete</span>
          </a>
        {% endif %}
      </p>

    {% else %}
      <p id="reply-options-{{message.pk}}">
        {% if message.sender.username != request.user.username and not hide_delete %}
          <button id="reply-button-{{message.pk}}" class="reply-button btn btn-primary" type="button" name="button">Reply</button>
          <button id="email-button-{{message.pk}}" class="email-button btn btn-primary" type="button" name="button">Email</button>
          {% if message.sender.profile.textable == True %}
            <button id="text-button-{{message.pk}}" class="text-button btn btn-primary" type="button" name="button">Text</button>
          {% endif %}
          <a class='pm-delete' href="{% url 'private_messages:delete' pk=message.pk %}" title="delete" class="btn btn-simple">
            <span class="glyphicon glyphicon-remove text-danger"></span>
            <span class="text-danger icon-label">Delete</span>
          </a>
        {% endif %}
      </p>

    {% endif %}

  {% endif %}
</div>

private_messages/templates/private_messages/_message.html
<div id="inbox-message-{{message.pk}}">
  <h3 id="subject_line">
    subject: <a href="{% url 'private_messages:detail' pk=message.pk %}">{{message.subject}}</a>
  </h3>
  <p>
    sent by: {{message.sender.username}}
  </p>
  <p>
    {% if user.is_authenticated and not hide_delete %}
      <a class='pm-delete' href="{% url 'private_messages:delete' pk=message.pk %}" title="delete" class="btn btn-simple">
        <span class="glyphicon glyphicon-remove text-danger"></span>
        <span class="text-danger icon-label">Delete</span>
      </a>
    {% endif %}
  </p>
</div>

private_messages/templates/private_messages/_sent_message.html
<div id="outbox-message-{{message.pk}}">
  {% if msgdetail == "True" %}
    <h3 class="subject_line">subject: {{message.subject}}</h3>
  {% else %}
    <h3 class="subject_line">subject: <a href="{% url 'private_messages:detail' pk=message.pk %}">{{message.subject}}</a></h3>
  {% endif %}
  <p>sent to: {{message.recipient.username}}</p>
  <p>
    {% if privatemessage.recipient.username == request.user.username %}
        <a class='pm-delete' href="{% url 'private_messages:delete' pk=message.pk %}" title="delete" class="btn btn-simple">
        <span class="glyphicon glyphicon-remove text-danger"></span>
        <span class="text-danger icon-label">Delete</span>
      </a>
    {% endif %}
  </p>
</div>

private_messages/templates/private_messages/new_message.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
  <div class='new-message-form'>
    <h1>New Message</h1>
    <form method="post">
      {% csrf_token %}
      {% bootstrap_form message_form %}
      <input type='submit' class='btn btn-primary' value='Send Message'>
    </form>
  </div>
  {% endblock %}

private_messages/templates/private_messages/privatemessage_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  {% include "private_messages/_message.html" with message=object hide_delete=True %}
  <form method="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
    <a href="{% url 'private_messages:detail' pk=object.pk %}" class="btn btn-default">Cancel</a>
  </form>
{% endblock %}

private_messages/templates/private_messages/privatemessage_detail.html
{% extends "base.html" %}
{% block content %}
  <h3>Message: {{privatemessage.message}}</h3>
  {% if privatemessage.recipient.username == request.user.username %}
    {% include "private_messages/_inbox_message.html" with message=privatemessage msgdetail="True" %}
  {% else %}
    {% include "private_messages/_sent_message.html" with message=privatemessage msgdetail="True" %}
  {% endif %}
{% endblock %}

private_messages/templates/private_messages/privatemessage_list.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'private_messages/style.css' %}" />

{% block javascript %}
  <script>
    function cancelMessage(){
      document.getElementById('new-message-div').classList.add('hidden')
      document.getElementById('new-message-button').classList.remove('hidden')
    }
    document.getElementById('cancel-message').addEventListener('click', cancelMessage);

    $('.inbox-messages').on('submit', 'form', function(e) {
      e.preventDefault();
      var that = $(this)
      var recipientId = that.prev().prev().attr('id').slice(10,that.prev().prev().attr('id').length)
      if (that.attr('class') == 'reply-message'){
        var msgId = that.attr('id').slice(11,that.attr('id').length)
        var subject = document.getElementById('reply-subject-'+msgId).value;
        var message = document.getElementById('reply-message-'+msgId).value;
        sendReply();
        function sendReply() {
          $.ajax({
            url  : "{% url 'private_messages:new_message' %}",
            type : "POST",
            data : {
              recipient : recipientId,
              subject : subject,
              message : message
            },
            beforeSend: function (xhr) {
              xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
            },
            success : function() {
              document.getElementById('reply-form-'+msgId).classList.add('hidden');
              document.getElementById('inbox-options-'+msgId).classList.remove('hidden')
            }
          })
        }
      } else if (that.attr('class') == 'email-message') {
        var subject = document.getElementById('email-subject-'+msgId).value;
        var message = document.getElementById('email-message-'+msgId).value;
        var msgId = that.attr('id').slice(11,that.attr('id').length)
        sendEmail();
        function sendEmail() {
          $.ajax({
            url  : '{% url 'accounts:email' %}',
            type : "POST",
            data : {
              recipient : recipientId,
              subject : subject,
              message : message
            },
            beforeSend: function (xhr) {
              xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
            },
            success : function() {
              document.getElementById('email-form-'+msgId).classList.add('hidden');
              document.getElementById('inbox-options-'+msgId).classList.remove('hidden')
            }
          })
        }
      } else if (that.attr('class') == 'text-message') {
        var msgId = that.attr('id').slice(10,that.attr('id').length)
        var message = document.getElementById('text-message-'+msgId).value;
        sendText();
        function sendText() {
          $.ajax({
            url  : "{% url 'private_messages:text' %}",
            type : "POST",
            data : {
              recipient : recipientId,
              message : message
            },
            beforeSend: function (xhr) {
              xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
            },
            success : function() {
              document.getElementById('text-form-'+msgId).classList.add('hidden');
              document.getElementById('inbox-options-'+msgId).classList.remove('hidden')
            }
          })
        }
      }
    })

    $('#new-message-button').on('click',function(e){
      $('#new-message-div').removeClass('hidden');
      $('#new-message-button').addClass('hidden');
    })

    $('#new-message-div').on('submit','form',function(e){
      e.preventDefault();
      that = $(this)
      sendMessage();
      function sendMessage(){
        $.ajax({
          url  : "{% url 'private_messages:new_message' %}",
          type : "POST",
          data : { recipient: $('#id_recipient').val(), subject: $('#id_subject').val(), message: $('#id_message').val() },
          beforeSend: function (xhr) {
            xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
          },
          success : function(json) {
            document.getElementById('new-message-div').classList.add('hidden')
            document.getElementById('id_recipient').value = '';
            document.getElementById('id_subject').value = '';
            document.getElementById('id_message').value = '';
            $('#new-message-button').removeClass('hidden');
            if (json.recipient_id == json.sender_id) {
              $('.inbox-messages').prepend("<div id='inbox-message-"+json.message_pk+"'><h3 id='subject_line'>subject: <a class='inbox-msg-"+json.message_pk+"' href='/messages/details/"+json.message_pk+"/'>"+json.subject+"</a></h3><p>sent by: "+json.username+"</a></p><p><a class='pm-delete' href='/messages/delete/"+json.message_pk+"/' title='delete' class='btn btn-simple'><span class='glyphicon glyphicon-remove text-danger'></span><span class='text-danger icon-label'>Delete</span></a></p></div>")
              $('.outbox-messages').prepend("<div id='outbox-message-"+json.message_pk+"'><h3 id='subject_line'>subject: <a class='outbox-msg-"+json.message_pk+"' href='/messages/details/"+json.message_pk+"/'>"+json.subject+"</a></h3><p>sent to: "+json.recipient+"</a></p></div>")
            } else {
              $('.outbox-messages').prepend("<div id='outbox-message-"+json.message_pk+"'><h3 id='subject_line'>subject: <a class='outbox-msg-"+json.message_pk+"' href='/messages/details/"+json.message_pk+"/'>"+json.subject+"</a></h3><p>sent to: "+json.recipient+"</a></p></div>")
            }
          }
        })
      }
    })
  </script>
  <script type="text/javascript" src="/static/js/asynch_communications.js"></script>
{% endblock %}

{% block content %}
  <div class="new-message">
    <h1>Inbox</h1>
    <a id="new-message-button" href="#">New Message</a>
    <div id='new-message-div' class='hidden'>
      <h1>New Message</h1>
      <form method="post">
        {% csrf_token %}
        {% bootstrap_form message_form %}
        <p>
          <input type='submit' class='btn btn-primary' value='Send Message'>
          <button id="cancel-message" class='btn btn-primary' type="button" name="button">Cancel</button>
        </p>
      </form>
    </div>
  </div>
  <div class="inbox-messages">
    {% for message in users_inbox  %}
      {% include "private_messages/_inbox_message.html" %}
    {% endfor %}
  </div>
  <h1>Sent Messages</h1>
  <div class="outbox-messages">
    {% for message in users_outbox  %}
      {% include "private_messages/_sent_message.html" %}
    {% endfor %}
  </div>
{% endblock %}