accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'


urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
    url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),
    url(r'^profile/(?P<pk>\d+)/$', views.view_profile, name='profile'),
    url(r'^email/$', views.send_email, name='email'),
    url(r'^delete/founditem/(?P<pk>\d+)/$', views.DeleteFoundItem, name='found_delete'),
    url(r'^delete/lostitem/(?P<pk>\d+)/$', views.DeleteLostItem, name='lost_delete'),
]

mainpage/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from homepage.views import Home
from homepage import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Home.as_view(), name='home'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^private_messages/',include('private_messages.urls',namespace='private_messages')),
    url(r'^createlostitem/', views.CreateLostItem, name='createlostitem'),
    url(r'^createfounditem/', views.CreateFoundItem, name='createfounditem'),
]

accounts/models.py
# from django.db import models
from django.contrib import auth
from django.utils import timezone
from django.contrib.auth import models
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

class User(auth.models.User, auth.models.PermissionsMixin):

    class Meta:
        auto_created = True

    def __str__(self):
        return "@{}".format(self.get_username())

# # our user profile, (one to one linked model that corresponds with a specific user)
class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), related_name='user_profile', on_delete=models.CASCADE)
    phone_number = models.TextField(max_length=500, blank=True)
    emailable = models.BooleanField()
    textable = models.BooleanField()
#
# # this code "attaches" these methods to the user model, and calls them whenever a save event occurs
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from homepage.models import Profile
from django.contrib.auth.models import User

class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ('username','email','password1','password2')
        model = get_user_model()

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('phone_number', 'emailable', 'textable')

accounts/views.py
from django.contrib.auth import login, logout
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView,DetailView
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
User = get_user_model()
from django.http import JsonResponse
from django.views import generic
from django.views import View
from django.shortcuts import render,redirect
from homepage.models import FoundItem,LostItem
from django.contrib.auth.decorators import login_required
from django.db import transaction
from .forms import UserForm,ProfileForm
from . import forms
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect

def send_email(request):
    subject = request.POST.get('subject', '')
    message = request.POST.get('message', '')
    from_email = request.POST.get('recipient', '')
    recipient_user = get_object_or_404(User, pk=from_email)
    sending_user = get_object_or_404(User, pk=from_email)
    if subject and message and from_email:
        try:
            send_mail(subject, message, sending_user.email, [recipient_user.email])
        except BadHeaderError:
            return HttpResponse('Invalid header found.')
        return HttpResponseRedirect('/contact/thanks/')
    else:
        return HttpResponse('Make sure all fields are entered and valid.')

def validate_username(request):
    username = request.GET.get('username', None)
    data = {
        'is_taken': User.objects.filter(username__iexact=username).exists()
    }
    if data['is_taken']:
        data['error_message'] = 'A user with this username already exists.'
    return JsonResponse(data)

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("home")
    template_name = "accounts/signup.html"

@login_required
@transaction.atomic
def view_profile(request, **kwargs):
    if request.is_ajax():
        this_user = get_object_or_404(User, pk=kwargs['pk'])
        response_data = {}
        if this_user.email != request.POST['emailAddress']:
            this_user.email = request.POST['emailAddress']
        if this_user.username != request.POST['userName']:
            this_user.username = request.POST['userName']
        this_user.profile.phone_number = request.POST['phoneNumber']
        if request.POST['emailableOption'] == 'true':
            this_user.profile.emailable = True
        else:
            this_user.profile.emailable = False
        if request.POST['textableOption'] == 'true':
            this_user.profile.textable = True
        else:
            this_user.profile.textable = False
        this_user.save()
        this_user.profile.save()
        response_data['userName'] = request.POST['userName']
        response_data['pk'] = kwargs['pk']
        return JsonResponse(response_data)
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('accounts:profile', pk=kwargs['pk'])
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
        user_lost_items = User.objects.all().prefetch_related('lostitems').get(id = kwargs['pk'])
        user_found_items = User.objects.all().prefetch_related('founditems').get(id = kwargs['pk'])
        users = User.objects.all().select_related('profile').get(id = kwargs['pk'])
    return render(request, 'accounts/profile.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'user_lost_items': user_lost_items.lostitems.all(),
        'user_found_items': user_found_items.founditems.all()
    })

def DeleteFoundItem(request, **kwargs):
    founditem = get_object_or_404(FoundItem, pk=kwargs['pk'])
    founditem.delete()
    user_id = founditem.user.pk
    if request.is_ajax():
        response_data = {}
        response_data['pk'] = kwargs['pk']
        return JsonResponse(response_data)
    return redirect('accounts:profile', pk=user_id)

def DeleteLostItem(request, **kwargs):
    lostitem = get_object_or_404(LostItem, pk=kwargs['pk'])
    lostitem.delete()
    user_id = lostitem.user.pk
    if request.is_ajax():
        response_data = {}
        response_data['pk'] = kwargs['pk']
        return JsonResponse(response_data)
    return redirect('accounts:profile', pk=user_id)

accounts/templates/accounts/_item.html
  <p>
    {{item.description}}
    <a id="{{item.id}}" class="{{name}}" href="#" title="delete">delete</a>
  </p>

accounts/templates/accounts/login.html
{% load bootstrap3 %}
<div class="nav-element">
    <form method="POST">
        {% csrf_token %}
        <input type="text" name="username" value="" placeholder="username">
        <input type="password" name="password" value="" placeholder="password">
        <input type="submit" value="Login" class="btn btn-default">
        or
        <button type="button" name="button"><a href="{% url 'accounts:signup' %}">Sign Up</a></button>
    </form>
</div>

accounts/templates/accounts/profile.html
    {% extends "base.html" %}
    {% block content %}
      <div class="">
        <h1 id="user-greeting">hi {{user.username}}</h1>
        <h3>Feel free to delete any items that have been reunited with their owner</h3>
      </div>
      <div class="user-found-item-list">
        <p><b>Items you've found</b></p>
        {% for item in user_found_items %}
          {% include "accounts/_item.html" with item=item name="founditem" %}
        {% endfor %}
      </div>
      <div class="user-lost-item-list">
        <p><b>Items you've lost</b></p>
        {% for item in user_lost_items %}
          {% include "accounts/_item.html" with item=item name="lostitem" %}
        {% endfor %}
      </div>
      <div class="user-contact-info">
        <h2>Edit your information</h2>
        <form id="edit-user-info-{{user.id}}" method="post">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <button type="submit">Save changes</button>
        </form>
      </div>
    {% endblock %}
    {% block javascript %}
    <script>
      $('#edit-user-info-{{user.id}}').on('submit',function(e){
        e.preventDefault();
        var that = $(this)
        var idLength = that.attr('id').length
        var userName = document.getElementById("id_username").value;
        var emailAddress = document.getElementById("id_email").value;
        var phoneNumber = document.getElementById("id_phone_number").value;
        var emailableOption = document.getElementById("id_emailable").checked;
        var textableOption = document.getElementById("id_textable").checked;
        if(textableOption == true) {
          if (phoneNumber.length < 11) {
            alert('If you want to be able to recieve text messages you must enter a valid phone number')
          } else {
            updateUserInfo();
          }
        } else {
          updateUserInfo();
        }
        function updateUserInfo() {
          $.ajax({
            url  : '/accounts/profile/'+that.attr('id').slice((15),idLength)+"/",
            type : "POST",
            data : {
              pk : that.attr('id').slice((idLength-1),idLength),
              phoneNumber : phoneNumber,
              emailableOption : emailableOption,
              textableOption : textableOption,
              userName : userName,
              emailAddress : emailAddress
            },
            beforeSend: function (xhr) {
              xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
            },
            success : function(json) {
              document.getElementById("user-greeting").innerHTML = 'hi '+json['userName']
            }
          })
        }
      })
        $('.founditem').on('click',function(e){
          e.preventDefault();
          var that = $(this)
          deleteFoundItem();
          function deleteFoundItem() {
            $.ajax({
              url  : "/accounts/delete/"+that.attr('class')+"/"+that.attr('id'),
              type : "DELETE",
              beforeSend: function (xhr) {
                xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
              },
              success : function(json) {
                that.parent().detach()
              }
            })
          }
        })
        $('.lostitem').on('click',function(e){
          e.preventDefault();
          var that = $(this)
          deleteLostItem();
          function deleteLostItem() {
            $.ajax({
              url  : "/accounts/delete/"+that.attr('class')+"/"+that.attr('id'),
              type : "DELETE",
              beforeSend: function (xhr) {
                xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
              },
              success : function(json) {
                that.parent().detach()
              }
            })
          }
        })
      </script>
    {% endblock %}

accounts/templates/accounts/signup.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>signup</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  </head>
  <body>
    {% load bootstrap3 %}
    <div class="container">
      <h1>Sign Up</h1>

      <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-default" value="Sign Up">
      </form>
    </div>
    <script>
      $("#id_username").change(function () {
        var username = $(this).val();

        $.ajax({
          url: '{% url 'accounts:validate_username' %}',
          data: {
            'username': username
          },
          dataType: 'json',
          success: function (data) {
            if (data.is_taken) {
              alert(data.error_message);
            }
          }
        });

      });
    </script>
  </body>
</html>