accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'


urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
    url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),
    url(r'^profile/(?P<pk>\d+)/$', views.view_profile, name='profile'),
    url(r'^email/$', views.send_email, name='email'),
    url(r'^delete/founditem/(?P<pk>\d+)/$', views.DeleteFoundItem, name='found_delete'),
    url(r'^delete/lostitem/(?P<pk>\d+)/$', views.DeleteLostItem, name='lost_delete'),
]

mainpage/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from homepage.views import Home
from homepage import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Home.as_view(), name='home'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^private_messages/',include('private_messages.urls',namespace='private_messages')),
    url(r'^createlostitem/', views.CreateLostItem, name='createlostitem'),
    url(r'^createfounditem/', views.CreateFoundItem, name='createfounditem'),
]

private_messages/urls.py
from django.conf.urls import url
from . import views

app_name = 'private_messages'

urlpatterns = [
    url(r'^$',views.PrivateMessageList.as_view(),name='list'),
    url(r'^new/$',views.CreatePrivateMessage,name='new_message'),
    url(r'^text/$',views.CreateText,name='text'),
    url(r'^details/(?P<pk>\d+)/$',views.PrivateMessageDetail.as_view(),name='detail'),
    url(r'^delete/(?P<pk>\d+)/$',views.DeletePrivateMessage,name='delete'),
    url(r'^deletehome/(?P<pk>\d+)/$',views.DeletePrivateMessageHome,name='deletehome'),
]

templates/base.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Stack Overclone{% endblock %}</title>

    {# jquery, needed here for bootstraps javascript #}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>
  <body>
    <nav class="navbar mynav" role='navigation' id='navbar'>
      <div class="container">
        <ul class='nav navbar-nav navbar-right'>
          {% if user.is_authenticated %}
            <li><a class='navbar-brand mynav' href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'accounts:profile' pk=request.user.pk %}">Profile</a></li>
            <li><a href="{% url 'private_messages:list' %}"class="btn btn-simple">Messages</a></li>
            <li><a href="{% url 'accounts:logout' %}"class="btn btn-simple">Log Out</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block content %}{% endblock %}
    </div>

    {% block javascript %}{% endblock %}
    {% block partial_javascript %}{% endblock %}
  </body>
</html>